### ISSUE TITLE
语音对讲问题

### ISSUE THREAD

**Issue by colin354** [MengFanLu1/wvp-gb28181-talk-demo#1]
您好，非常感谢您的分享，我拉取代码后点击语音对讲报了个Error
可以帮忙看一下是啥原因么？
![image](https://user-images.githubusercontent.com/20513374/228721097-ccfdaa78-fb5c-4196-a71c-f406dd04ab76.png)

**Comment by MengFanLu1** [comment]
> 您好，非常感谢您的分享，我拉取代码后点击语音对讲报了个Error 可以帮忙看一下是啥原因么？ ![image](https://user-images.githubusercontent.com/20513374/228721097-ccfdaa78-fb5c-4196-a71c-f406dd04ab76.png)

明天我提交下代码，又更新了下对讲流程，你再试试
